<h1>Chapter 2 - Tokens and Token Embeddings</h1>
<i>Exploring tokens and embeddings as an integral part of building LLMs</i>


<a href="https://www.amazon.com/Hands-Large-Language-Models-Understanding/dp/1098150961"><img src="https://img.shields.io/badge/Buy%20the%20Book!-grey?logo=amazon"></a>
<a href="https://www.oreilly.com/library/view/hands-on-large-language/9781098150952/"><img src="https://img.shields.io/badge/O'Reilly-white.svg?logo=data:image/svg%2bxml;base64,PHN2ZyB3aWR0aD0iMzQiIGhlaWdodD0iMjciIHZpZXdCb3g9IjAgMCAzNCAyNyIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iMTMiIGN5PSIxNCIgcj0iMTEiIHN0cm9rZT0iI0Q0MDEwMSIgc3Ryb2tlLXdpZHRoPSI0Ii8+CjxjaXJjbGUgY3g9IjMwLjUiIGN5PSIzLjUiIHI9IjMuNSIgZmlsbD0iI0Q0MDEwMSIvPgo8L3N2Zz4K"></a>
<a href="https://github.com/HandsOnLLM/Hands-On-Large-Language-Models"><img src="https://img.shields.io/badge/GitHub%20Repository-black?logo=github"></a>
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/HandsOnLLM/Hands-On-Large-Language-Models/blob/main/chapter02/Chapter%202%20-%20Tokens%20and%20Token%20Embeddings.ipynb)

---

This notebook is for Chapter 2 of the [Hands-On Large Language Models](https://www.amazon.com/Hands-Large-Language-Models-Understanding/dp/1098150961) book by [Jay Alammar](https://www.linkedin.com/in/jalammar) and [Maarten Grootendorst](https://www.linkedin.com/in/mgrootendorst/).

---

<a href="https://www.amazon.com/Hands-Large-Language-Models-Understanding/dp/1098150961">
<img src="https://raw.githubusercontent.com/HandsOnLLM/Hands-On-Large-Language-Models/main/images/book_cover.png" width="350"/></a>

### [OPTIONAL] - Installing Packages on <img src="https://colab.google/static/images/icons/colab.png" width=100>

If you are viewing this notebook on Google Colab (or any other cloud vendor), you need to **uncomment and run** the following codeblock to install the dependencies for this chapter:

---

💡 **NOTE**: We will want to use a GPU to run the examples in this notebook. In Google Colab, go to
**Runtime > Change runtime type > Hardware accelerator > GPU > GPU type > T4**.

---

In [56]:
%%capture
!pip install --upgrade transformers==4.41.2 sentence-transformers==3.0.1 gensim==4.3.2 scikit-learn==1.5.0 accelerate==0.31.0 peft==0.11.1 scipy==1.10.1 numpy==1.26.4

# Downloading and Running An LLM

The first step is to load our model onto the GPU for faster inference. Note that we load the model and tokenizer separately and keep them as such so that we can explore them separately.

In [2]:
from transformers import AutoModelForCausalLM, AutoTokenizer

# Load model and tokenizer
model = AutoModelForCausalLM.from_pretrained(
    "microsoft/Phi-3-mini-4k-instruct",
    device_map="cuda",
    torch_dtype="auto",
    trust_remote_code=False,
)
tokenizer = AutoTokenizer.from_pretrained("microsoft/Phi-3-mini-4k-instruct")

config.json:   0%|          | 0.00/967 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors.index.json:   0%|          | 0.00/16.5k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/195 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/181 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/3.44k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.94M [00:00<?, ?B/s]

tokenizer.model: reconstructing file:   0%|          |  0.00B /  500kB

tokenizer.model: downloading bytes:           |  0.00B

added_tokens.json:   0%|          | 0.00/306 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/599 [00:00<?, ?B/s]

In [16]:
prompt = "Write a procedure to buy a car from dealership. Explain how to buy the car using finanace.<|assistant|>"

# Tokenize the input prompt
input_ids = tokenizer(prompt, return_tensors="pt").input_ids.to("cuda")

# Generate the text
generation_output = model.generate(
  input_ids=input_ids,
  max_new_tokens=235
)

# Print the output
print(tokenizer.decode(generation_output[0]))

Write a procedure to buy a car from dealership. Explain how to buy the car using finanace.<|assistant|> Buying a car from a dealership involves several steps, including financing if you don't have the full amount available upfront. Here's a general procedure to guide you through the process:

1. Research and choose a car:
   - Determine your budget and the type of car you want.
   - Research different models, features, and prices.
   - Compare prices and features from various dealerships.

2. Get pre-approved for financing:
   - Before visiting the dealership, get pre-approved for a car loan from a bank, credit union, or online lender.
   - This will give you an idea of your loan terms, interest rates, and monthly payments.
   - Having pre-approved financing can also give you an advantage when negotiating with the dealership.

3. Visit the dealership:
   - Schedule a test drive and visit the dealership to see the car in person.
   - Take the car for a test drive to ensure it meets your expectations and requirements.

In [17]:
print(input_ids)

tensor([[14350,   263,  8792,   304, 15649,   263,  1559,   515,  5376, 10475,
         29889, 12027,  7420,   920,   304, 15649,   278,  1559,   773, 11782,
           815, 29889, 32001]], device='cuda:0')

In [18]:
for id in input_ids[0]:
   print(tokenizer.decode(id))

Write
a
procedure
to
buy
a
car
from
deal
ership
.
Exp
lain
how
to
buy
the
car
using
finan
ace
.
<|assistant|>

In [19]:
generation_output

tensor([[14350,   263,  8792,   304, 15649,   263,  1559,   515,  5376, 10475,
         29889, 12027,  7420,   920,   304, 15649,   278,  1559,   773, 11782,
           815, 29889, 32001,  5373,  5414,   263,  1559,   515,   263,  5376,
         10475, 20789,  3196,  6576, 29892,  3704, 11782,  3277,   565,   366,
          1016, 29915, 29873,   505,   278,  2989,  5253,  3625,   701,  8862,
         29889,  2266, 29915, 29879,   263,  2498,  8792,   304, 10754,   366,
          1549,   278,  1889, 29901,    13,    13, 29896, 29889, 10550,   322,
          6755,   263,  1559, 29901,    13,   259,   448,  5953,   837,   457,
           596, 23562,   322,   278,  1134,   310,  1559,   366,   864, 29889,
            13,   259,   448, 10550,  1422,  4733, 29892,  5680, 29892,   322,
         26094, 29889,    13,   259,   448,  3831,   598, 26094,   322,  5680,
           515,  5164,  5376,   414, 14587, 29889,    13,    13, 29906, 29889,
          3617,   758, 29899,  9961,  1490,   363, 11782,  3277, 29901,    13,
           259,   448, 10949,  6493,   292,   278,  5376, 10475, 29892,   679,
           758, 29899,  9961,  1490,   363,   263,  1559, 24806,   515,   263,
          9124, 29892, 16200,  9833, 29892,   470,  7395,   301,  1581, 29889,
            13,   259,   448,   910,   674,  2367,   366,   385,  2969,   310,
           596, 24806,  4958, 29892,  4066, 19257, 29892,   322,  4098,   368,
          5146,  1860, 29889,    13,   259,   448, 15950,   758, 29899,  9961,
          1490, 11782,  3277,   508,   884,  2367,   366,   385, 10631,   746,
         27214,  1218,   411,   278,  5376, 10475, 29889,    13,    13, 29941,
         29889,  5741,   277,   278,  5376, 10475, 29901,    13,   259,   448,
          1102, 11272,   263,  1243,  7899,   322,  6493,   278,  5376, 10475,
           304,  1074,   278,  1559,   297,  2022, 29889,    13,   259,   448,
         11190,   278,  1559,   363,   263,  1243,  7899,   304,  9801,   372,
         28103,   596,  2149,   800,   322, 11780, 29889,    13]],
       device='cuda:0')

In [20]:
print(tokenizer.decode(3323))
print(tokenizer.decode(622))
print(tokenizer.decode([3323, 622]))
print(tokenizer.decode(29901))

Sub
ject
Subject
:

# Comparing Trained LLM Tokenizers

In [21]:
from transformers import AutoModelForCausalLM, AutoTokenizer

colors_list = [
    '102;194;165', '252;141;98', '141;160;203',
    '231;138;195', '166;216;84', '255;217;47'
]

def show_tokens(sentence, tokenizer_name):
    tokenizer = AutoTokenizer.from_pretrained(tokenizer_name)
    token_ids = tokenizer(sentence).input_ids
    for idx, t in enumerate(token_ids):
        print(
            f'\x1b[0;30;48;2;{colors_list[idx % len(colors_list)]}m' +
            tokenizer.decode(t) +
            '\x1b[0m',
            end=' '
        )

In [25]:
text = """
Construction and SAFETY
🏗️ 建筑
token_test True None if != <= else: two spaces:"  " four spaces:"    "
25.5*40=1020
"""

In [23]:
show_tokens(text, "bert-base-uncased")

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

[CLS] bengali and culture [UNK] [UNK] show _ token ##s false none eli ##f = = > = else : two tab ##s : " " three tab ##s : " " 12 . 0 * 50 = 600 [SEP]

In [26]:
show_tokens(text, "bert-base-cased")

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

[CLS] Construction and SA ##F ##ET ##Y [UNK] [UNK] [UNK] token _ test True None if ! = < = else : two spaces : " " four spaces : " " 25 . 5 * 40 = 102 ##0 [SEP]

In [27]:
show_tokens(text, "gpt2")

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

 Construction  and  SAF ET Y
 � � � ️  � � � � � �
 token _ test  True  None  if  !=  <=  else :  two  spaces :"    "  four  spaces :"        "
 25 . 5 * 40 = 10 20

In [28]:
show_tokens(text, "google/flan-t5-small")

config.json:   0%|          | 0.00/1.40k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/2.54k [00:00<?, ?B/s]

spiece.model: reconstructing file:   0%|          |  0.00B /  792kB

spiece.model: downloading bytes:           |  0.00B

tokenizer.json:   0%|          | 0.00/2.42M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/2.20k [00:00<?, ?B/s]

Construction and SA FE TY  <unk>  <unk> token _ test True None  if  ! =  <unk> = else : two spaces : " " four spaces : " " 2 5.5 * 40 = 10 20 </s>

In [29]:
# The official is `tiktoken` but this the same tokenizer on the HF platform
show_tokens(text, "Xenova/gpt-4")

tokenizer_config.json:   0%|          | 0.00/460 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.01M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/917k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/98.0 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/4.23M [00:00<?, ?B/s]

 Construction  and  SAF ETY
 � � � ️  � � � � �
 token _ test  True  None  if  !=  <=  else :  two  spaces :"    "  four  spaces :"      "
 25 . 5 * 40 = 10 20

In [30]:
# You need to request access before being able to use this tokenizer
show_tokens(text, "bigcode/starcoder2-15b")

config.json:   0%|          | 0.00/803 [00:00<?, ?B/s]

[transformers] Model config: bos_token_id must be `None` or an integer within the vocabulary (between 0 and 49151), got 50256. This may result in unexpected behavior.
[transformers] Model config: eos_token_id must be `None` or an integer within the vocabulary (between 0 and 49151), got 50256. This may result in unexpected behavior.

tokenizer_config.json:   0%|          | 0.00/7.88k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/777k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/442k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/958 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.06M [00:00<?, ?B/s]

[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer GPT2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

 Construction  and  S AF ET Y
 � � ️   建 � �
 token _ test  True  None  if  !=  <=  else :  two  spaces :"    "  four  spaces :"      "
 2 5 . 5 * 4 0 = 1 0 2 0

In [31]:
show_tokens(text, "facebook/galactica-1.3b")

config.json:   0%|          | 0.00/789 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/166 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.14M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/3.00 [00:00<?, ?B/s]

 C onstruction  and  SAF ET Y
 � � � � � �  � � � � � �
 token _ test  True  None  if   ! =   < =  else :  two  spaces : "    "  four  spaces : "      "
 2 5 . 5 * 4 0 = 1 0 2 0

In [32]:
show_tokens(text, "microsoft/Phi-3-mini-4k-instruct")

 Const ruction and S AF ET Y
 � � � � ️  建 � � �
 token _ test True None if != <= else : two spaces :"  " four spaces :"    "
 2 5 . 5 * 4 0 = 1 0 2 0

# Contextualized Word Embeddings From a Language Model (Like BERT)

In [33]:
from transformers import AutoModel, AutoTokenizer

# Load a tokenizer
tokenizer = AutoTokenizer.from_pretrained("microsoft/deberta-base")

# Load a language model
model = AutoModel.from_pretrained("microsoft/deberta-v3-xsmall")

# Tokenize the sentence
tokens = tokenizer('Construction safety is important', return_tensors='pt')

# Process the tokens
output = model(**tokens)[0]

config.json:   0%|          | 0.00/474 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/578 [00:00<?, ?B/s]

pytorch_model.bin: reconstructing file:   0%|          |  0.00B /  241MB

pytorch_model.bin: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]

[transformers] DebertaV2Model LOAD REPORT from: microsoft/deberta-v3-xsmall
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
lm_predictions.lm_head.LayerNorm.bias      | UNEXPECTED |  |
mask_predictions.dense.bias                | UNEXPECTED |  |
mask_predictions.classifier.bias           | UNEXPECTED |  |
deberta.embeddings.word_embeddings._weight | UNEXPECTED |  |
mask_predictions.dense.weight              | UNEXPECTED |  |
lm_predictions.lm_head.dense.bias          | UNEXPECTED |  |
lm_predictions.lm_head.LayerNorm.weight    | UNEXPECTED |  |
lm_predictions.lm_head.bias                | UNEXPECTED |  |
mask_predictions.LayerNorm.bias            | UNEXPECTED |  |
mask_predictions.LayerNorm.weight          | UNEXPECTED |  |
lm_predictions.lm_head.dense.weight        | UNEXPECTED |  |
mask_predictions.classifier.weight         | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

model.safetensors: reconstructing file:   0%|          |  0.00B /  241MB

model.safetensors: downloading bytes:           |  0.00B

In [34]:
output.shape

torch.Size([1, 6, 384])

In [35]:
for token in tokens['input_ids'][0]:
    print(tokenizer.decode(token))

[CLS]
Construction
 safety
 is
 important
[SEP]

In [36]:
output

tensor([[[-3.5078, -0.0463, -0.1644,  ..., -0.0936, -0.2822,  0.3049],
         [-0.7095,  0.2010,  0.2749,  ..., -0.0983, -0.2433, -0.0731],
         [-0.6992, -0.0189,  0.2168,  ...,  1.1719,  0.1131,  0.9751],
         [ 0.1946,  0.3438, -0.0841,  ...,  0.3450,  0.2549,  1.8271],
         [ 0.2859, -0.3005,  0.3730,  ...,  1.1328,  0.2671, -0.5078],
         [-3.3848, -0.0417, -0.2568,  ...,  0.0759, -0.2939,  0.5000]]],
       dtype=torch.float16, grad_fn=<NativeLayerNormBackward0>)

# Text Embeddings (For Sentences and Whole Documents)

In [37]:
from sentence_transformers import SentenceTransformer

# Load model
model = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')

# Convert text to text embeddings
vector = model.encode("BIM improves construction project coordination")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/11.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  438MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [38]:
vector.shape

(768,)

# Word Embeddings Beyond LLMs

In [45]:
%pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.13/dist-packages (from gensim) (2.1.3)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.13/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.13/dist-packages (from gensim) (8.0.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.13/dist-packages (from smart_open>=1.8.1->gensim) (2.4.0)
Downloading gensim-4.4.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.8/27.8 MB 56.8 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [46]:
import gensim.downloader as api

# Download embeddings (66MB, glove, trained on wikipedia, vector size: 50)
# Other options include "word2vec-google-news-300"
# More options at https://github.com/RaRe-Technologies/gensim-data
model = api.load("glove-wiki-gigaword-50")

[==================================================] 100.0% 66.0/66.0MB downloaded

In [47]:
model.most_similar([model['king']], topn=11)

[('king', 1.0000001192092896),
 ('prince', 0.8236179351806641),
 ('queen', 0.7839043140411377),
 ('ii', 0.7746230363845825),
 ('emperor', 0.7736247777938843),
 ('son', 0.766719400882721),
 ('uncle', 0.7627150416374207),
 ('kingdom', 0.7542161345481873),
 ('throne', 0.7539914846420288),
 ('brother', 0.7492411136627197),
 ('ruler', 0.7434253692626953)]

# Recommending songs by embeddings

In [48]:
import pandas as pd
from urllib import request

# Get the playlist dataset file
data = request.urlopen('https://storage.googleapis.com/maps-premium/dataset/yes_complete/train.txt')

# Parse the playlist dataset file. Skip the first two lines as
# they only contain metadata
lines = data.read().decode("utf-8").split('\n')[2:]

# Remove playlists with only one song
playlists = [s.rstrip().split() for s in lines if len(s.split()) > 1]

# Load song metadata
songs_file = request.urlopen('https://storage.googleapis.com/maps-premium/dataset/yes_complete/song_hash.txt')
songs_file = songs_file.read().decode("utf-8").split('\n')
songs = [s.rstrip().split('\t') for s in songs_file]
songs_df = pd.DataFrame(data=songs, columns = ['id', 'title', 'artist'])
songs_df = songs_df.set_index('id')

In [49]:
print( 'Playlist #1:\n ', playlists[0], '\n')
print( 'Playlist #2:\n ', playlists[1])

Playlist #1:
  ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '2', '42', '43', '44', '45', '46', '47', '48', '20', '49', '8', '50', '51', '52', '53', '54', '55', '56', '57', '25', '58', '59', '60', '61', '62', '3', '63', '64', '65', '66', '46', '47', '67', '2', '48', '68', '69', '70', '57', '50', '71', '72', '53', '73', '25', '74', '59', '20', '46', '75', '76', '77', '59', '20', '43']

Playlist #2:
  ['78', '79', '80', '3', '62', '81', '14', '82', '48', '83', '84', '17', '85', '86', '87', '88', '74', '89', '90', '91', '4', '73', '62', '92', '17', '53', '59', '93', '94', '51', '50', '27', '95', '48', '96', '97', '98', '99', '100', '57', '101', '102', '25', '103', '3', '104', '105', '106', '107', '47', '108', '109', '110', '111', '112', '113', '25', '63', '62', '114', '115', '84', '116', '117', '118', '119', '120', '121', '122', '123', '50', '70', '71', '124', '17', '85', '14', '82', '48', '125', '47', '46', '72', '53', '25', '73', '4', '126', '59', '74', '20', '43', '127', '128', '129', '13', '82', '48', '130', '131', '132', '133', '134', '135', '136', '137', '59', '46', '138', '43', '20', '139', '140', '73', '57', '70', '141', '3', '1', '74', '142', '143', '144', '145', '48', '13', '25', '146', '50', '147', '126', '59', '20', '148', '149', '150', '151', '152', '56', '153', '154', '155', '156', '157', '158', '159', '160', '161', '162', '163', '164', '165', '166', '167', '168', '169', '170', '171', '172', '173', '174', '175', '60', '176', '51', '177', '178', '179', '180', '181', '182', '183', '184', '185', '57', '186', '187', '188', '189', '190', '191', '46', '192', '193', '194', '195', '196', '197', '198', '25', '199', '200', '49', '201', '100', '202', '203', '204', '205', '206', '207', '32', '208', '209', '210']

In [50]:
from gensim.models import Word2Vec

# Train our Word2Vec model
model = Word2Vec(
    playlists, vector_size=32, window=20, negative=50, min_count=1, workers=4
)

In [51]:
song_id = 2172

# Ask the model for songs similar to song #2172
model.wv.most_similar(positive=str(song_id))

[('5634', 0.9965460896492004),
 ('3167', 0.9959951043128967),
 ('3094', 0.9951716065406799),
 ('5549', 0.9950536489486694),
 ('2886', 0.9945782423019409),
 ('2640', 0.9936890602111816),
 ('2849', 0.9925290942192078),
 ('3105', 0.9921627640724182),
 ('6640', 0.9917781352996826),
 ('3114', 0.9913395643234253)]

In [52]:
print(songs_df.iloc[2172])

title     Fade To Black
artist        Metallica
Name: 2172 , dtype: object

In [53]:
import numpy as np

def print_recommendations(song_id):
    similar_songs = np.array(
        model.wv.most_similar(positive=str(song_id),topn=5)
    )[:,0]
    return  songs_df.iloc[similar_songs]

# Extract recommendations
print_recommendations(2172)

                  title         artist
id
5634     Mr. Brownstone  Guns N' Roses
3167          Unchained      Van Halen
3094   Breaking The Law   Judas Priest
5549      November Rain  Guns N' Roses
2886            The Zoo      Scorpions

In [54]:
print_recommendations(2172)

                  title         artist
id
5634     Mr. Brownstone  Guns N' Roses
3167          Unchained      Van Halen
3094   Breaking The Law   Judas Priest
5549      November Rain  Guns N' Roses
2886            The Zoo      Scorpions

In [55]:
print_recommendations(842)

,title,artist
id,,
18844,Murder She Wrote,Chaka Demus & Pliers
413,If I Ruled The World (Imagine That) (w\/ Laury...,Nas
27078,Out Of My Head (w\/ Trey Songz),Lupe Fiasco
9452,Hip Hop Hooray,Naughty By Nature
18843,Ting A Ling,Shabba Ranks